#!/usr/bin/python3

import sys
import Connection.py

def get_port(arg1):
	port = int(arg1)
	if port < 0 or port > 65535:
		return (-1)
	return (port)

def launch_graphic_client(arg1, arg2):
	port = get_port(arg1)
	host = arg2
	@Connection.connect_client(port, host)

def print_usage():
	print("USAGE")
	print("\t./zappy_graphique port host")

def main():
	if len(sys.argv) == 2 and sys.argv[1] == "--help":
		print_usage()
	elif len(sys.argv) == 3:
		launch_graphic_client(sys.argv[1], sys.argv[2])
	else:
		exit(84)
	exit(0)

main()